import React, { useState } from "react";
import { Button } from "react-bootstrap";

export enum Holiday {
    DragonBoatFestival = "Dragon Boat Festival 🎏",
    Halloween = "Halloween 🎃",
    Diwali = "Diwali 🪔",
    Christmas = "Christmas 🎄",
    Thanksgiving = "Thanksgiving 🦃"
}

export function CycleHoliday(): JSX.Element {
    const [currentHoliday, setCurrentHoliday] = useState<Holiday>(
        Holiday.DragonBoatFestival
    );

    const getNextHolidayAlphabetically = (current: Holiday): Holiday => {
        const holidaysInOrder = Object.values(Holiday).sort();
        const currentIndex = holidaysInOrder.findIndex(
            (holiday) => holiday === current
        );
        const nextIndex = (currentIndex + 1) % holidaysInOrder.length;
        return holidaysInOrder[nextIndex];
    };

    const getNextHolidayByYear = (current: Holiday): Holiday => {
        const holidaysByYear = [
            Holiday.Halloween,
            Holiday.Diwali,
            Holiday.DragonBoatFestival,
            Holiday.Thanksgiving,
            Holiday.Christmas
        ];
        const currentIndex = holidaysByYear.findIndex(
            (holiday) => holiday === current
        );
        const nextIndex = (currentIndex + 1) % holidaysByYear.length;
        return holidaysByYear[nextIndex];
    };

    return (
        <div>
            <div>Holiday: {currentHoliday}</div>
            <Button
                onClick={() =>
                    setCurrentHoliday(
                        getNextHolidayAlphabetically(currentHoliday)
                    )
                }
            >
                Advance by Alphabet
            </Button>
            <Button
                onClick={() =>
                    setCurrentHoliday(getNextHolidayByYear(currentHoliday))
                }
            >
                Advance by Year
            </Button>
        </div>
    );
}
//partially generated by chatgpt
